dir: ./.hashbase
brandname: Hashbase
hostname: hashbase.local
proxy: true
port: 8080
letsencrypt: false
sites: false
rateLimiting: true
csrf: true

defaultDiskUsageLimit: 100mb
defaultNamedArchivesLimit: 15
proDiskUsageLimit: 10gb
proNamedArchivesLimit: 100

# processing jobs
jobs:
  popularArchivesIndex: 30s
  userDiskUsage: 5m
  deleteDeadArchives: 5m

# cache settings
cache:
  metadataStorage: 65536
  contentStorage: 65536
  tree: 65536

# monitoring
pm2: true
alerts:
  diskUsage: 1gb

# user settings
registration:
  open: false
  allowed:
    - alice@mail.com
    - bob@mail.com
  reservedNames:
    - admin
    - root
    - support
    - noreply
    - users
    - archives
admin:
  email: ''
  password: ''

# email settings
email:
  transport: stub
  sender: '"Hashbase" <noreply@hashbase.local>'

# login sessions
sessions:
  algorithm: HS256
  secret: THIS MUST BE REPLACED!
  expiresIn: 1h
